$axure.loadCurrentPage({
  "url":"user_name_edit.html",
  "generationDate":new Date(1407573645513.87),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5670c76bc4ab44988c95f48f8655ce16",
    "type":"Axure:Page",
    "name":"user_name_edit",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c8be105ca21c405dbd292171d0b1eeef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":550,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3047b6869c64f00acd6b80cf29e0cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":550,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/user_name_edit/u0.png"}},
{
          "id":"6e1bdc9b2a6249c58198354aea7b901e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":11},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"089e5547d9eb4affab201ea0eb839eba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":12,
                  "y":11},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4bc3b99dca241d59f124e954a044e1e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":37},
            "size":{
              "width":327,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20bb936324bc44999d7b59a8d3b4badc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90a32755f455408e8cf84d423bbba9a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"87a47a4be3cd4aa19edb967bcee2dae1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"869362ecec904dd7877807cdc55dc20c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"e257be1c76f8455e8d38d06d0b459bd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":218,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"02b8b2a1f14042a9a791af0f3a7af990",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u5.png",
                "mouseOver~":"images/account_number_edit/u5_mouseOver.png"}},
{
              "id":"32d4e8b2461c41c5ba169e688d9ed5c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c5ca3c8e347e4eefaaf26392947cfff4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"91eeb37265fb47a88c54162b0c8d476b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14a0aab6972645e1807477a31c379cfc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"1d924faf463c4a7e8f97b04f6151ec6c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd732677382d40408c4704ed4c8162f4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"6dfe3baa4ca844b3827d3cb0684de515",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c41f92af796e4f9b86c3929c0a48b866",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"bf30da1697f1481a9c9fc352be3ccaac",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"daa180dd61aa45aaa77a6d2e385e2730",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"b2c0c4fc059f411788717ed3c8df499f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b2b724575964e9b8aa1a2c195ba8350",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png",
                "mouseOver~":"images/account_number_edit/u19_mouseOver.png"}},
{
              "id":"41efa25412f54f919528af91465e070b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":138},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"600552f059ee418c823a8b9362aa0eda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":138},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u21.png",
                "mouseOver~":"images/account_number_edit/u21_mouseOver.png"}}]},
{
          "id":"66890f9917b644858e66c235cd24902d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":111},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f0fcd62539e4fbaa5b1001cb72b1ff6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f704e9a786fc458cb91741c45f23bf5d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":183},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"19b548993364455ead4c5d6009af55e5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":72},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "c8be105ca21c405dbd292171d0b1eeef":{
      "scriptId":"u0"},
    "b3047b6869c64f00acd6b80cf29e0cd3":{
      "scriptId":"u1"},
    "6e1bdc9b2a6249c58198354aea7b901e":{
      "scriptId":"u2"},
    "089e5547d9eb4affab201ea0eb839eba":{
      "scriptId":"u3"},
    "c4bc3b99dca241d59f124e954a044e1e":{
      "scriptId":"u4"},
    "20bb936324bc44999d7b59a8d3b4badc":{
      "scriptId":"u5"},
    "90a32755f455408e8cf84d423bbba9a8":{
      "scriptId":"u6"},
    "e257be1c76f8455e8d38d06d0b459bd7":{
      "scriptId":"u7"},
    "02b8b2a1f14042a9a791af0f3a7af990":{
      "scriptId":"u8"},
    "87a47a4be3cd4aa19edb967bcee2dae1":{
      "scriptId":"u9"},
    "869362ecec904dd7877807cdc55dc20c":{
      "scriptId":"u10"},
    "32d4e8b2461c41c5ba169e688d9ed5c6":{
      "scriptId":"u11"},
    "c5ca3c8e347e4eefaaf26392947cfff4":{
      "scriptId":"u12"},
    "91eeb37265fb47a88c54162b0c8d476b":{
      "scriptId":"u13"},
    "14a0aab6972645e1807477a31c379cfc":{
      "scriptId":"u14"},
    "1d924faf463c4a7e8f97b04f6151ec6c":{
      "scriptId":"u15"},
    "bd732677382d40408c4704ed4c8162f4":{
      "scriptId":"u16"},
    "6dfe3baa4ca844b3827d3cb0684de515":{
      "scriptId":"u17"},
    "c41f92af796e4f9b86c3929c0a48b866":{
      "scriptId":"u18"},
    "bf30da1697f1481a9c9fc352be3ccaac":{
      "scriptId":"u19"},
    "daa180dd61aa45aaa77a6d2e385e2730":{
      "scriptId":"u20"},
    "b2c0c4fc059f411788717ed3c8df499f":{
      "scriptId":"u21"},
    "6b2b724575964e9b8aa1a2c195ba8350":{
      "scriptId":"u22"},
    "41efa25412f54f919528af91465e070b":{
      "scriptId":"u23"},
    "600552f059ee418c823a8b9362aa0eda":{
      "scriptId":"u24"},
    "66890f9917b644858e66c235cd24902d":{
      "scriptId":"u25"},
    "4f0fcd62539e4fbaa5b1001cb72b1ff6":{
      "scriptId":"u26"},
    "f704e9a786fc458cb91741c45f23bf5d":{
      "scriptId":"u27"},
    "19b548993364455ead4c5d6009af55e5":{
      "scriptId":"u28"}}});