$axure.loadCurrentPage({
  "url":"contact_number_edit.html",
  "generationDate":new Date(1407573645732.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c71d44670c3d4cab850c6bdf514161b1",
    "type":"Axure:Page",
    "name":"contact_number_edit",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"560570b72fe6447b80beae1d3090dbb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443438b1dce149dcbaed2f978b645497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account_number_edit/u0.png"}},
{
          "id":"ab02f45ea48344f7b73e91cf1d3b83bf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":327,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42458b266cf34d43882ca568b93673d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3b64338db414c3793cd74fcd2026b4e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"49239a74dbe549a7ac6486607dfbc564",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"022b840d893e4b5783dba0263177fd1c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"0dc8a4b810ca419da77c72356924c7f1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":218,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa97b89854cb4bb1abd0cfa7940a65c6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u5.png",
                "mouseOver~":"images/account_number_edit/u5_mouseOver.png"}},
{
              "id":"e6f23b30251e4ddeadad80acbeaf223d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ec8603c67be40bfb21c413f67849c65",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"af4e22360b264a32a10348609665cd0a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7662f06ac6e041f0802667906d2362e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"cea0e5ca095e4e2885b1a052eadfc389",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bd68a9ca1adb40a295086a0e2431927e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"95876a4693b142789db908ef4e7421d0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"60212bc1934d47d099576b1b3504d789",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"956be10ba64944d2a5eb01db65d537c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42b67e7f5b774d2a8d08fd9f35943791",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"f375dbf5a2884741a5bbc82155e735d3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83d48322e6f94c66a76f968bfe491229",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png",
                "mouseOver~":"images/account_number_edit/u19_mouseOver.png"}},
{
              "id":"8aada58a39c34f6cbfd17fd46aa24c63",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":138},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98970ff5b9bb47c4a5d36fa93380f5b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":138},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u21.png",
                "mouseOver~":"images/account_number_edit/u21_mouseOver.png"}}]},
{
          "id":"15717853bc39420db687e12fdd95acf2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":76},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0f8ed92532ce4764bd5c9ed5dbfe6f79",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":111},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dc905333aa2f4b40b89e8d476bf58cbe",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ddd7dae486364ef9a7d0dd9aafe84fa9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":183},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"660c7f6d417749bc9adf50e17e2782f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":14},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c4821f0d77146919008b31ff69d3be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "560570b72fe6447b80beae1d3090dbb5":{
      "scriptId":"u0"},
    "443438b1dce149dcbaed2f978b645497":{
      "scriptId":"u1"},
    "ab02f45ea48344f7b73e91cf1d3b83bf":{
      "scriptId":"u2"},
    "42458b266cf34d43882ca568b93673d9":{
      "scriptId":"u3"},
    "e3b64338db414c3793cd74fcd2026b4e":{
      "scriptId":"u4"},
    "0dc8a4b810ca419da77c72356924c7f1":{
      "scriptId":"u5"},
    "aa97b89854cb4bb1abd0cfa7940a65c6":{
      "scriptId":"u6"},
    "49239a74dbe549a7ac6486607dfbc564":{
      "scriptId":"u7"},
    "022b840d893e4b5783dba0263177fd1c":{
      "scriptId":"u8"},
    "e6f23b30251e4ddeadad80acbeaf223d":{
      "scriptId":"u9"},
    "9ec8603c67be40bfb21c413f67849c65":{
      "scriptId":"u10"},
    "af4e22360b264a32a10348609665cd0a":{
      "scriptId":"u11"},
    "7662f06ac6e041f0802667906d2362e3":{
      "scriptId":"u12"},
    "cea0e5ca095e4e2885b1a052eadfc389":{
      "scriptId":"u13"},
    "bd68a9ca1adb40a295086a0e2431927e":{
      "scriptId":"u14"},
    "95876a4693b142789db908ef4e7421d0":{
      "scriptId":"u15"},
    "60212bc1934d47d099576b1b3504d789":{
      "scriptId":"u16"},
    "956be10ba64944d2a5eb01db65d537c1":{
      "scriptId":"u17"},
    "42b67e7f5b774d2a8d08fd9f35943791":{
      "scriptId":"u18"},
    "f375dbf5a2884741a5bbc82155e735d3":{
      "scriptId":"u19"},
    "83d48322e6f94c66a76f968bfe491229":{
      "scriptId":"u20"},
    "8aada58a39c34f6cbfd17fd46aa24c63":{
      "scriptId":"u21"},
    "98970ff5b9bb47c4a5d36fa93380f5b5":{
      "scriptId":"u22"},
    "15717853bc39420db687e12fdd95acf2":{
      "scriptId":"u23"},
    "0f8ed92532ce4764bd5c9ed5dbfe6f79":{
      "scriptId":"u24"},
    "dc905333aa2f4b40b89e8d476bf58cbe":{
      "scriptId":"u25"},
    "ddd7dae486364ef9a7d0dd9aafe84fa9":{
      "scriptId":"u26"},
    "660c7f6d417749bc9adf50e17e2782f5":{
      "scriptId":"u27"},
    "6c4821f0d77146919008b31ff69d3be8":{
      "scriptId":"u28"}}});