$axure.loadCurrentPage({
  "url":"account_bank_edit.html",
  "generationDate":new Date(1407573645451.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b3ed7d4cb834d2fa9d4739d3d649d3b",
    "type":"Axure:Page",
    "name":"account_bank_edit",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3540ca590fa04d82941d7e1bf528ec7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e202ce4fabd47a2a7bb79aebc02ff01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account_number_edit/u0.png"}},
{
          "id":"076420b5d10a4c3eacb5edec82d794e7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":327,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b5ca349d5054369b10c106c9a448ffd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a7e1315c465439eb83590aab385ccb9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"552f485e186042b38bd2c10a1305dfba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"076e8d9c6cad497c92dc0910fc9ed179",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"83c6958263f04e919587ec61665f6063",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":218,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d959b1fda8714fa6bb402926de9b03bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u5.png",
                "mouseOver~":"images/account_number_edit/u5_mouseOver.png"}},
{
              "id":"28cd2ee3bd0e4db0ad4f534b23422869",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a45f1ce418a4c3a8164435a7f09492e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"11466eb859744ce28fd1a6ec3ee867fa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c3cdf7ff81964b51b4a1a2466bcc453c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"63b6ff6172dd4c01ae177a84c7d9d925",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"030c522a805b420aad7bbf57bf3f27a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"66330c8698f74ef1afef37a289d13c93",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5fa6a4b05b604c5c868db4a7a94eada9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"f623e6badead4819b53334205e0f2cc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9472e5459224f6f9bc93008fdd25935",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"5cf991e76c344cfba8b1b893d9c5ae68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f9b7d0f76da471d8b8c29a078afe66c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png",
                "mouseOver~":"images/account_number_edit/u19_mouseOver.png"}},
{
              "id":"d31f8cbe429e4e2682731672259dee58",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":138},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18a8768b3a77461d8a617157943d5dbc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":138},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u21.png",
                "mouseOver~":"images/account_number_edit/u21_mouseOver.png"}}]},
{
          "id":"f5e1b9f1c0b541b49c260726070c6bc1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":76},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"adf0bf90595347aca635f3bc5e38cc18",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":111},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2280d82546ff42c9a1d4b1238be626f1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"294345357d6d487a969ac4dd4c9973e6",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":183},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9c83676c788f44ffa093f5d8cd1286b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":14},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e79885dc03458fbb9c9280d589f23c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3540ca590fa04d82941d7e1bf528ec7b":{
      "scriptId":"u0"},
    "4e202ce4fabd47a2a7bb79aebc02ff01":{
      "scriptId":"u1"},
    "076420b5d10a4c3eacb5edec82d794e7":{
      "scriptId":"u2"},
    "2b5ca349d5054369b10c106c9a448ffd":{
      "scriptId":"u3"},
    "0a7e1315c465439eb83590aab385ccb9":{
      "scriptId":"u4"},
    "83c6958263f04e919587ec61665f6063":{
      "scriptId":"u5"},
    "d959b1fda8714fa6bb402926de9b03bb":{
      "scriptId":"u6"},
    "552f485e186042b38bd2c10a1305dfba":{
      "scriptId":"u7"},
    "076e8d9c6cad497c92dc0910fc9ed179":{
      "scriptId":"u8"},
    "28cd2ee3bd0e4db0ad4f534b23422869":{
      "scriptId":"u9"},
    "4a45f1ce418a4c3a8164435a7f09492e":{
      "scriptId":"u10"},
    "11466eb859744ce28fd1a6ec3ee867fa":{
      "scriptId":"u11"},
    "c3cdf7ff81964b51b4a1a2466bcc453c":{
      "scriptId":"u12"},
    "63b6ff6172dd4c01ae177a84c7d9d925":{
      "scriptId":"u13"},
    "030c522a805b420aad7bbf57bf3f27a8":{
      "scriptId":"u14"},
    "66330c8698f74ef1afef37a289d13c93":{
      "scriptId":"u15"},
    "5fa6a4b05b604c5c868db4a7a94eada9":{
      "scriptId":"u16"},
    "f623e6badead4819b53334205e0f2cc8":{
      "scriptId":"u17"},
    "f9472e5459224f6f9bc93008fdd25935":{
      "scriptId":"u18"},
    "5cf991e76c344cfba8b1b893d9c5ae68":{
      "scriptId":"u19"},
    "6f9b7d0f76da471d8b8c29a078afe66c":{
      "scriptId":"u20"},
    "d31f8cbe429e4e2682731672259dee58":{
      "scriptId":"u21"},
    "18a8768b3a77461d8a617157943d5dbc":{
      "scriptId":"u22"},
    "f5e1b9f1c0b541b49c260726070c6bc1":{
      "scriptId":"u23"},
    "adf0bf90595347aca635f3bc5e38cc18":{
      "scriptId":"u24"},
    "2280d82546ff42c9a1d4b1238be626f1":{
      "scriptId":"u25"},
    "294345357d6d487a969ac4dd4c9973e6":{
      "scriptId":"u26"},
    "9c83676c788f44ffa093f5d8cd1286b3":{
      "scriptId":"u27"},
    "d4e79885dc03458fbb9c9280d589f23c":{
      "scriptId":"u28"}}});