$axure.loadCurrentPage({
  "url":"user_address_edit.html",
  "generationDate":new Date(1407573645560.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"23f9ff2c1caa460b9ae7264cfd3ce3ec",
    "type":"Axure:Page",
    "name":"user_address_edit",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b97439612a2e4401a95d71b7684e6bc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":350,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71c189680df04b13910e8d9d4c20b132",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":350,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/user_address_edit/u0.png"}},
{
          "id":"dad0cc2f83cf4ff9afe56a72c9fb322b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":21},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37b44b8ba31149feaaef920badfe4459",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":21},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec0bd0df980d495eb06a390e83a9cda4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":47},
            "size":{
              "width":327,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e9857bb09544083ab5c926844a14c98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7ff2eac9eb849cd87af0552ea35def6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"302cc3dbbd6641409cbe14299dea9bf1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a9352d27f5e415b8f20b758f860748f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"64107ac5421d494094746cd55cb7e0cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":218,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a97c76e529c49bdaf7deb73288a8726",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u5.png",
                "mouseOver~":"images/account_number_edit/u5_mouseOver.png"}},
{
              "id":"2496d8cc526045a39b55984d34c7d47d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c48c099c79d94a27a594ed55ec508a33",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"d7df4b4370e24baf8bdbd66a0fce95bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4415ce08816041589acb4eb86cfb2739",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"7a4753e2a4074a4581a2f002b6113d2d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"85e1e4afb25b47b583dbe5e7df4a0063",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"9ea2beb3d14e4bc28781ec19059fdb8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67a971a8b9d54c8387f63d6a96363090",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"aaea53affe7844eb879670a5d2ba5795",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9eacc2ce4c845818de90309c793b153",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"1c9b968af1954b65a80e7bc157309d7b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cae1c297ac3645499fd6e0e4b7288832",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png",
                "mouseOver~":"images/account_number_edit/u19_mouseOver.png"}},
{
              "id":"fef88fd52e714763b0bcac83da51ef83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":138},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1a39005e99f4baf903cb2fd71feb086",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":138},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u21.png",
                "mouseOver~":"images/account_number_edit/u21_mouseOver.png"}}]},
{
          "id":"c6522ffa68714c399c270451b921b30d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":140,
              "y":121},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c08c6c7965e04679959f33db7344777a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":140,
              "y":156},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b228e620b3644da5b588decf4dc689c8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":193},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"85179f1d0a4f49338b3437b583beceae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":82},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "b97439612a2e4401a95d71b7684e6bc9":{
      "scriptId":"u0"},
    "71c189680df04b13910e8d9d4c20b132":{
      "scriptId":"u1"},
    "dad0cc2f83cf4ff9afe56a72c9fb322b":{
      "scriptId":"u2"},
    "37b44b8ba31149feaaef920badfe4459":{
      "scriptId":"u3"},
    "ec0bd0df980d495eb06a390e83a9cda4":{
      "scriptId":"u4"},
    "6e9857bb09544083ab5c926844a14c98":{
      "scriptId":"u5"},
    "d7ff2eac9eb849cd87af0552ea35def6":{
      "scriptId":"u6"},
    "64107ac5421d494094746cd55cb7e0cc":{
      "scriptId":"u7"},
    "1a97c76e529c49bdaf7deb73288a8726":{
      "scriptId":"u8"},
    "302cc3dbbd6641409cbe14299dea9bf1":{
      "scriptId":"u9"},
    "6a9352d27f5e415b8f20b758f860748f":{
      "scriptId":"u10"},
    "2496d8cc526045a39b55984d34c7d47d":{
      "scriptId":"u11"},
    "c48c099c79d94a27a594ed55ec508a33":{
      "scriptId":"u12"},
    "d7df4b4370e24baf8bdbd66a0fce95bb":{
      "scriptId":"u13"},
    "4415ce08816041589acb4eb86cfb2739":{
      "scriptId":"u14"},
    "7a4753e2a4074a4581a2f002b6113d2d":{
      "scriptId":"u15"},
    "85e1e4afb25b47b583dbe5e7df4a0063":{
      "scriptId":"u16"},
    "9ea2beb3d14e4bc28781ec19059fdb8a":{
      "scriptId":"u17"},
    "67a971a8b9d54c8387f63d6a96363090":{
      "scriptId":"u18"},
    "aaea53affe7844eb879670a5d2ba5795":{
      "scriptId":"u19"},
    "e9eacc2ce4c845818de90309c793b153":{
      "scriptId":"u20"},
    "1c9b968af1954b65a80e7bc157309d7b":{
      "scriptId":"u21"},
    "cae1c297ac3645499fd6e0e4b7288832":{
      "scriptId":"u22"},
    "fef88fd52e714763b0bcac83da51ef83":{
      "scriptId":"u23"},
    "e1a39005e99f4baf903cb2fd71feb086":{
      "scriptId":"u24"},
    "c6522ffa68714c399c270451b921b30d":{
      "scriptId":"u25"},
    "c08c6c7965e04679959f33db7344777a":{
      "scriptId":"u26"},
    "b228e620b3644da5b588decf4dc689c8":{
      "scriptId":"u27"},
    "85179f1d0a4f49338b3437b583beceae":{
      "scriptId":"u28"}}});