$axure.loadCurrentPage({
  "url":"account_number_edit.html",
  "generationDate":new Date(1407573645404.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"249708343ab646e1906dd5f0ac824f3f",
    "type":"Axure:Page",
    "name":"account_number_edit",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b8d458a8a9e14232ab56feed5584baf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":350,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26a45eb166a546188c414f460c492c95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":350,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account_number_edit/u0.png"}},
{
          "id":"b44e084da29c4a038de43a767aeb4f8d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":327,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48fe279d5624598a992d4106939d536",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"debaa7f3808347c9a8748e1c8372c9e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"1ecc3ed1f10b46a88d4e814420252d55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d270f8e17fb346be8919f9cfb8fe780c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"ca8b3153e0214d5e84a1be01446ef081",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":218,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa180abbf7b8481c9af4a4b742a0ee00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":218,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u5.png",
                "mouseOver~":"images/account_number_edit/u5_mouseOver.png"}},
{
              "id":"cc074e96a53745ce804c4eed7e4dfccc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3017160b38a04fde96a6b31467be27ea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"19b8383c6bf641a986168dabb265dd5b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b5144d5be0a34acb8ebaadae461e3830",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"c57379ab0edf473d9cb603adfbcb9d0e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"69ea4f3c5a344768b78a33d8660b2289",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"160546dfab5441ce827e7787b85354c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11b0b4c5f1144268a0b0a2c219948228",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png",
                "mouseOver~":"images/account_number_edit/u7_mouseOver.png"}},
{
              "id":"ca3101cf830c4f0585bea6a54222f46e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0c866fc9aecd40f49a33671b28970e7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u9.png",
                "mouseOver~":"images/account_number_edit/u9_mouseOver.png"}},
{
              "id":"1e0471ce692f456ab5dd2ed813cf4cda",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":0,
                  "y":138},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"67d347b03b704ef6990f98b5dbdb3440",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":0,
                      "y":138},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png",
                "mouseOver~":"images/account_number_edit/u19_mouseOver.png"}},
{
              "id":"2e0a49c0f0794045b7d1b9fe6af91906",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":109,
                  "y":138},
                "size":{
                  "width":218,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12eba8978ee348cd832fce0bef4ca274",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}}},
                    "location":{
                      "x":109,
                      "y":138},
                    "size":{
                      "width":218,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_number_edit/u21.png",
                "mouseOver~":"images/account_number_edit/u21_mouseOver.png"}}]},
{
          "id":"19fc6c9b5fec4986a839226f5a9a4795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":14},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5e13416fa8e4a8fab99df6254160374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e71f02a8c2524513b661326a3b0da628",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":76},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c22e7720c77e4de791a530cce7668469",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":111},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"81436ae608974fb1b26d0ad912859c44",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF333333,
              "opacity":1},
            "location":{
              "x":130,
              "y":146},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c9701634ab3f48439af6256408669c43",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":183},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "b8d458a8a9e14232ab56feed5584baf0":{
      "scriptId":"u0"},
    "26a45eb166a546188c414f460c492c95":{
      "scriptId":"u1"},
    "b44e084da29c4a038de43a767aeb4f8d":{
      "scriptId":"u2"},
    "a48fe279d5624598a992d4106939d536":{
      "scriptId":"u3"},
    "debaa7f3808347c9a8748e1c8372c9e6":{
      "scriptId":"u4"},
    "ca8b3153e0214d5e84a1be01446ef081":{
      "scriptId":"u5"},
    "aa180abbf7b8481c9af4a4b742a0ee00":{
      "scriptId":"u6"},
    "1ecc3ed1f10b46a88d4e814420252d55":{
      "scriptId":"u7"},
    "d270f8e17fb346be8919f9cfb8fe780c":{
      "scriptId":"u8"},
    "cc074e96a53745ce804c4eed7e4dfccc":{
      "scriptId":"u9"},
    "3017160b38a04fde96a6b31467be27ea":{
      "scriptId":"u10"},
    "19b8383c6bf641a986168dabb265dd5b":{
      "scriptId":"u11"},
    "b5144d5be0a34acb8ebaadae461e3830":{
      "scriptId":"u12"},
    "c57379ab0edf473d9cb603adfbcb9d0e":{
      "scriptId":"u13"},
    "69ea4f3c5a344768b78a33d8660b2289":{
      "scriptId":"u14"},
    "160546dfab5441ce827e7787b85354c6":{
      "scriptId":"u15"},
    "11b0b4c5f1144268a0b0a2c219948228":{
      "scriptId":"u16"},
    "ca3101cf830c4f0585bea6a54222f46e":{
      "scriptId":"u17"},
    "0c866fc9aecd40f49a33671b28970e7e":{
      "scriptId":"u18"},
    "1e0471ce692f456ab5dd2ed813cf4cda":{
      "scriptId":"u19"},
    "67d347b03b704ef6990f98b5dbdb3440":{
      "scriptId":"u20"},
    "2e0a49c0f0794045b7d1b9fe6af91906":{
      "scriptId":"u21"},
    "12eba8978ee348cd832fce0bef4ca274":{
      "scriptId":"u22"},
    "19fc6c9b5fec4986a839226f5a9a4795":{
      "scriptId":"u23"},
    "b5e13416fa8e4a8fab99df6254160374":{
      "scriptId":"u24"},
    "e71f02a8c2524513b661326a3b0da628":{
      "scriptId":"u25"},
    "c22e7720c77e4de791a530cce7668469":{
      "scriptId":"u26"},
    "81436ae608974fb1b26d0ad912859c44":{
      "scriptId":"u27"},
    "c9701634ab3f48439af6256408669c43":{
      "scriptId":"u28"}}});