$axure.loadCurrentPage({
  "url":"contact_info.html",
  "generationDate":new Date(1407573645623.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6a42576e4d80492b9f407af2994fcf16",
    "type":"Axure:Page",
    "name":"contact_info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"29e12e36440e44e5a82081884b2da28c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":520,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5373f7f88f0b47eba125963498dea6eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account_info/u0.png"}},
{
          "id":"924b1f19fc8d448e94c8ae4a000ec48c",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":497,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d04c91ef2004ee1b7287e40de86b6bd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"db7b1ba84c8f4741993d229369fc8040",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"c1b5dd6b8f3e4d769071fb2135702055",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11b7f3abef2d45d2b379d0f9ebed21ed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"e49da244a23248b68d973a631ae64836",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f56ff8a8dd57423a82ee3386069f1b25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"9fb23d3563bc4d5aba06385e409dee4f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48be7c002ff147ceaeb841def053fbbd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u5.png"}},
{
              "id":"12544ebfa5524c51b56b21d8f743afdb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4967e935c6f04b15a10ed735e040c58c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u11.png"}},
{
              "id":"869677934d9c4cf0a6dd3ed0be20ce9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fbba83e4bded4c23ab93c471310da074",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u11.png"}},
{
              "id":"5773b7c2ff6a473fa39909058039868e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":238,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"243b9ae20c474f2d8f565b7778233c6f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":0},
                    "size":{
                      "width":238,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u7.png"}},
{
              "id":"348ff7a83c624b2cbceb8c644057f32b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":30},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"137f975a9fbe409d9420871988b6dc82",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":30},
                    "size":{
                      "width":238,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u13.png"}},
{
              "id":"861f1fb6c4c142c2aa005351f306b3a1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":66},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"332a737394a24d38b65ded6d00fa53ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":66},
                    "size":{
                      "width":238,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u13.png"}},
{
              "id":"576dbd1885a24a04b560fdf435b1a0f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"280dae24db884719b8b7a1e63fec386c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png"}},
{
              "id":"fb11a02db08e4aaeb9b39afc408632d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":150,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7cc988fc9f341c3a5de2eac9b4f355e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":150,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u23.png"}},
{
              "id":"f9a363dbf58342d0bb38a4af923fae02",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":259,
                  "y":102},
                "size":{
                  "width":238,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"889e11099e1343fdada67871bb93dd53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":259,
                      "y":102},
                    "size":{
                      "width":238,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/contact_info/u25.png"}}]},
{
          "id":"0335c818a210415cb1cb5bfd821f4b18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":14},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b72270762e54b63878454224bdf085c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1dec91f62f8b481bbf8f31b9fb2619c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":14},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a43ff34f8f74343b20b74847194ead4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":427,
                  "y":14},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a31b37fbc064e96ace536eaca512a60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":80},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e0e9509b3b5419ab78fd9118d15f15a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":80},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c3734d7ab1046bb9013c3badeb302f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":80},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f9ef91da847467c9cf596cddae45809",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":80},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eec53c52099435fa0598c1692f32719",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":114},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77fbf02bcd7a410aa2469e181e778f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":114},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddc3008b3f5343369e7b795642f92da0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":114},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"791485c0477f44928baa02f01880329c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":114},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8620f407a51c4ba7b63c196767f881ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":154},
            "size":{
              "width":78,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"159ffccc039f49ecb35fc0412c13d43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":351,
                  "y":154},
                "size":{
                  "width":78,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"744f7ad2550d45a2a55f0782f527f8cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":154},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45cd336d55e84c1f860907e295d2e83f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":154},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "29e12e36440e44e5a82081884b2da28c":{
      "scriptId":"u0"},
    "5373f7f88f0b47eba125963498dea6eb":{
      "scriptId":"u1"},
    "924b1f19fc8d448e94c8ae4a000ec48c":{
      "scriptId":"u2"},
    "7d04c91ef2004ee1b7287e40de86b6bd":{
      "scriptId":"u3"},
    "db7b1ba84c8f4741993d229369fc8040":{
      "scriptId":"u4"},
    "9fb23d3563bc4d5aba06385e409dee4f":{
      "scriptId":"u5"},
    "48be7c002ff147ceaeb841def053fbbd":{
      "scriptId":"u6"},
    "5773b7c2ff6a473fa39909058039868e":{
      "scriptId":"u7"},
    "243b9ae20c474f2d8f565b7778233c6f":{
      "scriptId":"u8"},
    "c1b5dd6b8f3e4d769071fb2135702055":{
      "scriptId":"u9"},
    "11b7f3abef2d45d2b379d0f9ebed21ed":{
      "scriptId":"u10"},
    "12544ebfa5524c51b56b21d8f743afdb":{
      "scriptId":"u11"},
    "4967e935c6f04b15a10ed735e040c58c":{
      "scriptId":"u12"},
    "348ff7a83c624b2cbceb8c644057f32b":{
      "scriptId":"u13"},
    "137f975a9fbe409d9420871988b6dc82":{
      "scriptId":"u14"},
    "e49da244a23248b68d973a631ae64836":{
      "scriptId":"u15"},
    "f56ff8a8dd57423a82ee3386069f1b25":{
      "scriptId":"u16"},
    "869677934d9c4cf0a6dd3ed0be20ce9e":{
      "scriptId":"u17"},
    "fbba83e4bded4c23ab93c471310da074":{
      "scriptId":"u18"},
    "861f1fb6c4c142c2aa005351f306b3a1":{
      "scriptId":"u19"},
    "332a737394a24d38b65ded6d00fa53ce":{
      "scriptId":"u20"},
    "576dbd1885a24a04b560fdf435b1a0f4":{
      "scriptId":"u21"},
    "280dae24db884719b8b7a1e63fec386c":{
      "scriptId":"u22"},
    "fb11a02db08e4aaeb9b39afc408632d9":{
      "scriptId":"u23"},
    "d7cc988fc9f341c3a5de2eac9b4f355e":{
      "scriptId":"u24"},
    "f9a363dbf58342d0bb38a4af923fae02":{
      "scriptId":"u25"},
    "889e11099e1343fdada67871bb93dd53":{
      "scriptId":"u26"},
    "0335c818a210415cb1cb5bfd821f4b18":{
      "scriptId":"u27"},
    "3b72270762e54b63878454224bdf085c":{
      "scriptId":"u28"},
    "1dec91f62f8b481bbf8f31b9fb2619c0":{
      "scriptId":"u29"},
    "4a43ff34f8f74343b20b74847194ead4":{
      "scriptId":"u30"},
    "2a31b37fbc064e96ace536eaca512a60":{
      "scriptId":"u31"},
    "6e0e9509b3b5419ab78fd9118d15f15a":{
      "scriptId":"u32"},
    "3c3734d7ab1046bb9013c3badeb302f8":{
      "scriptId":"u33"},
    "6f9ef91da847467c9cf596cddae45809":{
      "scriptId":"u34"},
    "1eec53c52099435fa0598c1692f32719":{
      "scriptId":"u35"},
    "77fbf02bcd7a410aa2469e181e778f5e":{
      "scriptId":"u36"},
    "ddc3008b3f5343369e7b795642f92da0":{
      "scriptId":"u37"},
    "791485c0477f44928baa02f01880329c":{
      "scriptId":"u38"},
    "8620f407a51c4ba7b63c196767f881ae":{
      "scriptId":"u39"},
    "159ffccc039f49ecb35fc0412c13d43b":{
      "scriptId":"u40"},
    "744f7ad2550d45a2a55f0782f527f8cc":{
      "scriptId":"u41"},
    "45cd336d55e84c1f860907e295d2e83f":{
      "scriptId":"u42"}}});