$axure.loadCurrentPage({
  "url":"account_info.html",
  "generationDate":new Date(1407573645310.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d3b483dc64054cd3b0e2a54fd12d52f4",
    "type":"Axure:Page",
    "name":"account_info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1dbfef7bbaad4e5eb4bef87e7a78ceac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":520,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21697fbcaf374fb0b8974cbef94f4919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":520,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/account_info/u0.png"}},
{
          "id":"fa77e27447c3449d923e434fdfda3a21",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":497,
              "height":138}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e4cc7e11a43484682dd99d977d8c2ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":109,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7c136017b0394859a2a728dba37a2a1b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":109,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u3.png"}},
{
              "id":"7ac41134a27f4130bb054e1581f49dc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"66cdc83f6ca1429cb0b0ec5623fca4fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"efd7931961d34a41a981253475e63fdd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23c2e34a8a714a68bab826e8213eddac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u9.png"}},
{
              "id":"7abe0cc07e5a4e928399940fcee8caf4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":0},
                "size":{
                  "width":179,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f5ff403f160433bacd79f1c43f4efda",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":0},
                    "size":{
                      "width":179,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u5.png"}},
{
              "id":"1fed26a14a284386ac76d5f949ec85e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":30},
                "size":{
                  "width":179,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5ae2dd2a109b4bf49ed579b5389453b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":30},
                    "size":{
                      "width":179,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u11.png"}},
{
              "id":"c650c16c4fb8467485db2ea64b1e66d9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":66},
                "size":{
                  "width":179,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fee08e9515e148c9b8be5ccf3335a3d5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":179,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u11.png"}},
{
              "id":"1902b99f64c04d86ba27dda8cfd8a03f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":0},
                "size":{
                  "width":209,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51cc9725e4524dab878491e3ea48ea12",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":288,
                      "y":0},
                    "size":{
                      "width":209,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u7.png"}},
{
              "id":"65b3020b7c7840fbb0cc7cbaa290ce91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":30},
                "size":{
                  "width":209,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18a105dc55154735bb1cb38559e58b2f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":288,
                      "y":30},
                    "size":{
                      "width":209,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u13.png"}},
{
              "id":"768e754e0bd14d1ab67608b507e4fe7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":66},
                "size":{
                  "width":209,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"145fc63bc17b48eb9fce0834c6716e02",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":288,
                      "y":66},
                    "size":{
                      "width":209,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u13.png"}},
{
              "id":"7545c88bdbe34b488a9961c36c77bfb5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":102},
                "size":{
                  "width":109,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab448c7a93f849faa50f5979c824b42d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":109,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u21.png"}},
{
              "id":"97d5c3a614634cce8b1109d75bfdd8ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":109,
                  "y":102},
                "size":{
                  "width":179,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5661f5244844584a91e044b26dc9ede",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":109,
                      "y":102},
                    "size":{
                      "width":179,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u23.png"}},
{
              "id":"2020c3bbd10b444a962e04d3ad06d59f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":102},
                "size":{
                  "width":209,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3769e5ddc0c04ab7bc122aa434da3675",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":288,
                      "y":102},
                    "size":{
                      "width":209,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/account_info/u25.png"}}]},
{
          "id":"dcf37823424b4fd986264d399736028b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":14},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3c8dd4a64d41cab778017fb54a20e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":14},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4bbfa6157b349a890668f40066ccd7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":448,
              "y":14},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39cdc14a67f448a2837f3a369449f632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":448,
                  "y":14},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"289ef777a8ac4abeb94ac43ad060e898",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":80},
            "size":{
              "width":144,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b270a546795e4025a5e4caa8d9687336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":80},
                "size":{
                  "width":144,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 account_bank_edit",
                      "target":{
                        "targetType":"page",
                        "url":"account_bank_edit.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4a25df153f24874835f7b7e27a93064",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":114},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f31ad5bc9c604d4b9fa477637a26b402",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":114},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6438a83da9d47048cbe24b67e02adf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":154},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1e9ef4fe004f119fedb393b737df76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":154},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9270b0df441841f898d06516e6ef16b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":80},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87311dba28b34f2b8b32b2f5268c021d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":80},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 account_number_edit",
                      "target":{
                        "targetType":"page",
                        "url":"account_number_edit.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f80c1c4164a48fe859208eb1ffc7a7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":114},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2bd62f7d9e447f09b32d63912822f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":114},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e3c04b860254728b869c9e1b4f73479",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":336,
              "y":154},
            "size":{
              "width":134,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5aa9cc38354038988560a3bdd90a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":336,
                  "y":154},
                "size":{
                  "width":134,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1dbfef7bbaad4e5eb4bef87e7a78ceac":{
      "scriptId":"u0"},
    "21697fbcaf374fb0b8974cbef94f4919":{
      "scriptId":"u1"},
    "fa77e27447c3449d923e434fdfda3a21":{
      "scriptId":"u2"},
    "0e4cc7e11a43484682dd99d977d8c2ae":{
      "scriptId":"u3"},
    "7c136017b0394859a2a728dba37a2a1b":{
      "scriptId":"u4"},
    "7abe0cc07e5a4e928399940fcee8caf4":{
      "scriptId":"u5"},
    "5f5ff403f160433bacd79f1c43f4efda":{
      "scriptId":"u6"},
    "1902b99f64c04d86ba27dda8cfd8a03f":{
      "scriptId":"u7"},
    "51cc9725e4524dab878491e3ea48ea12":{
      "scriptId":"u8"},
    "7ac41134a27f4130bb054e1581f49dc5":{
      "scriptId":"u9"},
    "66cdc83f6ca1429cb0b0ec5623fca4fa":{
      "scriptId":"u10"},
    "1fed26a14a284386ac76d5f949ec85e2":{
      "scriptId":"u11"},
    "5ae2dd2a109b4bf49ed579b5389453b1":{
      "scriptId":"u12"},
    "65b3020b7c7840fbb0cc7cbaa290ce91":{
      "scriptId":"u13"},
    "18a105dc55154735bb1cb38559e58b2f":{
      "scriptId":"u14"},
    "efd7931961d34a41a981253475e63fdd":{
      "scriptId":"u15"},
    "23c2e34a8a714a68bab826e8213eddac":{
      "scriptId":"u16"},
    "c650c16c4fb8467485db2ea64b1e66d9":{
      "scriptId":"u17"},
    "fee08e9515e148c9b8be5ccf3335a3d5":{
      "scriptId":"u18"},
    "768e754e0bd14d1ab67608b507e4fe7d":{
      "scriptId":"u19"},
    "145fc63bc17b48eb9fce0834c6716e02":{
      "scriptId":"u20"},
    "7545c88bdbe34b488a9961c36c77bfb5":{
      "scriptId":"u21"},
    "ab448c7a93f849faa50f5979c824b42d":{
      "scriptId":"u22"},
    "97d5c3a614634cce8b1109d75bfdd8ee":{
      "scriptId":"u23"},
    "a5661f5244844584a91e044b26dc9ede":{
      "scriptId":"u24"},
    "2020c3bbd10b444a962e04d3ad06d59f":{
      "scriptId":"u25"},
    "3769e5ddc0c04ab7bc122aa434da3675":{
      "scriptId":"u26"},
    "dcf37823424b4fd986264d399736028b":{
      "scriptId":"u27"},
    "1b3c8dd4a64d41cab778017fb54a20e6":{
      "scriptId":"u28"},
    "d4bbfa6157b349a890668f40066ccd7e":{
      "scriptId":"u29"},
    "39cdc14a67f448a2837f3a369449f632":{
      "scriptId":"u30"},
    "289ef777a8ac4abeb94ac43ad060e898":{
      "scriptId":"u31"},
    "b270a546795e4025a5e4caa8d9687336":{
      "scriptId":"u32"},
    "c4a25df153f24874835f7b7e27a93064":{
      "scriptId":"u33"},
    "f31ad5bc9c604d4b9fa477637a26b402":{
      "scriptId":"u34"},
    "e6438a83da9d47048cbe24b67e02adf1":{
      "scriptId":"u35"},
    "ab1e9ef4fe004f119fedb393b737df76":{
      "scriptId":"u36"},
    "9270b0df441841f898d06516e6ef16b5":{
      "scriptId":"u37"},
    "87311dba28b34f2b8b32b2f5268c021d":{
      "scriptId":"u38"},
    "8f80c1c4164a48fe859208eb1ffc7a7f":{
      "scriptId":"u39"},
    "f2bd62f7d9e447f09b32d63912822f1b":{
      "scriptId":"u40"},
    "2e3c04b860254728b869c9e1b4f73479":{
      "scriptId":"u41"},
    "9a5aa9cc38354038988560a3bdd90a4c":{
      "scriptId":"u42"}}});